# Generates pretty snake animation, using @Platane's awesome snk action
name: "🐍 Generate Snake Contribution GIF"
on:
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '30 23 * * *' # Runs at 23:30 every day.
jobs:
  snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: "Generate Snake"
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-snake.gif
            assets/github-snake.svg
            assets/github-snake.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Commit the changes
      - name: "Push changes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "t.boulanger456@gmail.com"
          git config user.name "zareefy"
          git add .
          git commit -m ":snake: Updates Snake Contribution Animation"
          git push origin main
